// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    /**
     * Creates a new AppSettings instance.
     * @param {Partial<AppSettings>} [$$source = {}] - The source object to create the AppSettings.
     */
    constructor($$source = {}) {
        if (!("launchOnStartup" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["launchOnStartup"] = false;
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppSettings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings(/** @type {Partial<AppSettings>} */($$parsedSource));
    }
}

export class StickerItem {
    /**
     * Creates a new StickerItem instance.
     * @param {Partial<StickerItem>} [$$source = {}] - The source object to create the StickerItem.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("packId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["packId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dataUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataUrl"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StickerItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StickerItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StickerItem(/** @type {Partial<StickerItem>} */($$parsedSource));
    }
}

export class StickerPack {
    /**
     * Creates a new StickerPack instance.
     * @param {Partial<StickerPack>} [$$source = {}] - The source object to create the StickerPack.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("thumbDataUrl" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["thumbDataUrl"] = "";
        }
        if (!("count" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new StickerPack instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {StickerPack}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new StickerPack(/** @type {Partial<StickerPack>} */($$parsedSource));
    }
}
